### PR TITLE
mavlinkTask stats in CLI

### PR DESCRIPTION
**Pull request by rotorman**
Prepared mavlinkTask output to CLI stats, also fixed output of CLI stats to show uniformly bytes. Currently CLI and TELEMETRY_MAVLINK cannot yet be compiled at the same time to actually print out via serial the stats.
If CLI/DEBUG are enabled, bootloader build tries to enable serial port for itself, but cannot find _auxSerialTxFifo_, as this gets currently only declared when TELEMETRY_MAVLINK is NOT enabled:

https://github.com/olliw42/opentx/blob/875a4e98ec069cc0f42ed0d6a2c7b3df149b1342/radio/src/targets/common/arm/stm32/aux_serial_driver.cpp#L30-L35

### CODE REVIEW

**Comment by olliw42** [comment]
@rotorman 

Hey Risto, thx for the PR. I'm looking at it, but I don't understand the PR. In another issue you are saying that one can't compile with either CLI or DEBUG or both and TELEMETRY_MAVLINK at the same time. So, how can this PR possibly work????

Pl indicate what needs to be changed in order to get it working with DEBUG, CLI, or both.
Olli

**Comment by rotorman** [comment]
Hi @olliw42,
this is first a theoretical PR, it will only work AFTER the issue in #2 has been remedied. In my understanding, currently compiling with CLI and DEBUG options together with TELEMETRY_MAVLINK, auxSerialTxFifo does not get declared in aux_serial_driver.cpp, and this is required for the bootloader when compiled with DEBUG set.
If you could try compiling with CLI and DEBUG set in addition to TELEMETRY_MAVLINK, then you should see the error. I tried to change the code to fix this, but did not end with a successful code, so was not able to provide a working PR fix for the issue #2.

**Comment by olliw42** [comment]
many thx for the response. 

Pl, "theoretical" PRs are not useful. At minimum please indicate this VERY clearly, so it can be noted immediately. Like that you are just killing people's time.

Also, I just compiled with CLI=YES (and for T16), and as indicated before I do get a CCM memory overflow error. So, no idea how you possibly could have gotten this PR to work, even with the other issue resolved.

Btw, I don't think that your byte counting change is correct, but that's a side story.

I'm thus closing this, but pl don't feel turned down, but rather feel encouraged to propose a working code :)

**Comment by rotorman** [comment]
It would be great if you could look into compiling your OpenTX fork with CLI and DEBUG enabled and make the necessary changes to achieve this. Thank you!

**Comment by olliw42** [comment]
I just spend the whole morning on this, but gave up now. I honestly have to say that it is not high enough on my list of priorities that I want to spend more time on this.

**Comment by rotorman** [comment]
I can relate to your frustration, because I tried as well, but there were quite a few changes from vanilla OpenTX involved that needed a change back or a special case handling, so that this ended me changing more and more of your code, so I abandoned doing them myself. Nevertheless, in the long run, I do believe this should be tackled. Likely better sooner than later, as later the code might deviate from vanilla even more...

**Comment by olliw42** [comment]
I in addition got the impression that also the bootloader is somehow affected ... and that's really not what I want to go into. It's not really frustration, it's just that I'm not interested enough into getting this done, there are other things which are more important to me. And in addition, this is open source, so anyone can jump in ... that's at least what all these os folks say is the advantage of it, right ;)

**Comment by rotorman** [comment]
As I understood, the bootloader is only affected by the fact that you disabled the original auxSerialTxFifo in case TELEMETRY_MAVLINK is defined. And this variable is used by bootloader if DEBUG and CLI are enabled.
Thus my idea was to keep it (but with your increased depth *2) and then work from that. Nevertheless moving auxSerialTxFifo back from mavlink_telem.cpp to it's previous aux_serial_driver.cpp needed more than a few changes to your code parts and I thought this might be better handled by you as you surely know your code better than I do.

**Comment by olliw42** [comment]
well, the problem is that it doesn't only have twice the size but that I've also located it in a different memory ... and I've put all that into the mavtel file to keep it together ... one would need to reorganize that, but as said, I've spend enough time on it for what it is worth it.

and as pointed out twice now, that's not only that, there is also the cli overflow issue

**Comment by rotorman** [comment]
Please do not take this comment the wrong way - is meant just as information - on vanilla CLI works without problems.

**Comment by olliw42** [comment]
no idea what this proves
but I certainly don't take it the wrong way

**Pull request closed without merging**
